name: Generate GitHub Metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Trophies
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-trophies.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          base: ""
          plugin_trophy: yes
          plugin_trophy_theme: flat
          plugin_trophy_rank: SSS, SS, S, AAA, AA, A, B, C
          config_theme: tokyonight

      - name: Generate Core Stats
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-stats.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          base: header, repositories
          plugin_lines: yes
          config_timezone: Asia/Kolkata
          config_theme: tokyonight
